parameters:
    quest: CoreBundle\Entity\Quest
    time: CoreBundle\Entity\Time
    time_history: CoreBundle\Entity\TimeHistory
    city: CoreBundle\Entity\City
    visit: CoreBundle\Entity\Visit
    type_game: CoreBundle\Entity\TypeGame
    page: CoreBundle\Entity\Page

services:
    quest.handler:
        class: CoreBundle\Handler\QuestHandler
        arguments: [@service_container, %quest%]
    time.handler:
        class: CoreBundle\Handler\TimeHandler
        arguments: [@service_container, %time%]
    time_history.handler:
        class: CoreBundle\Handler\TimeHistoryHandler
        arguments: [@service_container, %time_history%]
    city.handler:
        class: CoreBundle\Handler\CityHandler
        arguments: [@service_container, %city%]
    visit.handler:
        class: CoreBundle\Handler\VisitHandler
        arguments: [@service_container, %visit%]
    page.handler:
        class: CoreBundle\Handler\PageHandler
        arguments: [@service_container, %page%]

    admin.quest:
        class: CoreBundle\Admin\QuestAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-gamepad"></i>', group: "Квесты", label: "Квесты" }
        arguments:
            - ~
            - %quest%
            - 'SonataAdminBundle:CRUD'

    type.quest:
        class: CoreBundle\Admin\TypeGameAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-gamepad"></i>', group: "Квесты", label: "Тип" }
        arguments:
            - ~
            - %type_game%
            - 'SonataAdminBundle:CRUD'

    admin.time:
        class: CoreBundle\Admin\TimeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-clock-o"></i>', group: "Время", label: "Время" }
        arguments:
            - ~
            - %time%
            - 'SonataAdminBundle:CRUD'

    admin.visit:
        class: CoreBundle\Admin\VisitAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-clock-o"></i>', group: "Время", label: "Часы" }
        arguments:
            - ~
            - %visit%
            - 'SonataAdminBundle:CRUD'

    admin.city:
        class: CoreBundle\Admin\CityAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-globe"></i>', group: "Города", label: "Города", on_top: true }
        arguments:
            - ~
            - %city%
            - 'SonataAdminBundle:CRUD'

    admin.page:
        class: CoreBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-globe"></i>', group: "Страницы", label: "Страницы", on_top: true }
        arguments:
            - ~
            - %page%
            - 'SonataAdminBundle:CRUD'